### PR TITLE
Update github_actions.rb

### PR DESCRIPTION
**Pull request by RishabhTayal**
I am not sure where to update the [danger.systems](https://danger.systems/guides/getting_started.html) website documentation so I am doing it here. I hope this is the right place.

Changing the docker image from `duck8823/actions/danger` to `duck8823/danger`.

### CODE REVIEW

**Comment by orta** [comment]
These can probably move to `danger/danger` now that #1063 is in?

**Comment by RishabhTayal** [comment]
@orta Did you publish the docker image to the hub?

**Comment by RishabhTayal** [comment]
I will make the change once you push it here: https://hub.docker.com/u/dangersystems

**Comment by orta** [comment]
GitHub actions supports using the repo by default: https://developer.github.com/actions/creating-workflows/workflow-configuration-options/#using-a-dockerfile-image-in-an-action

**Comment by RishabhTayal** [comment]
Updated.

**Comment by orta** [comment]
ace

**Pull request merged**
