### PR TITLE
Fix FileList returning arrays

### PR DESCRIPTION
**Pull request by sleekybadger**
## Summary

Fixes https://github.com/danger/danger/issues/155. This can't be done via normal subclassing without overriding a lot of methods, so i decided to do this in delegation way. 

Please note, that:

```
class List; include Danger::Helpers::ArraySublcass; end
class OtherList; include Danger::Helpers::ArraySublcass; end

List.new([1, 2, 3]) == OtherList.new([1, 2 ,3])
=> false

List.new([1, 2, 3]) == [1, 2 ,3]
=> false

List.new([1, 2, 3]) == List.new([1, 2, 3])
=> true

List.new([1, 2, 3]).is_a?(Array)
=> true

List.new([1, 2, 3]).is_a?(OtherList)
=> false
```

But this can be changed easily.

### CODE REVIEW

**Comment by sleekybadger** [comment]
AppVeyor exits with something weird. Can someone take a look?

**Comment by orta** [comment]
Sorry - [was preparing to get married](https://www.facebook.com/orta.therox/videos/870147662790/) when you sent this PR, so I completely missed it :D

**Comment by orta** [comment]
OK, I've re-run the build. 👍 

Can you please change the `appveyor.yml` to look like this:

```yml
install:
  - set PATH=C:\Ruby22\bin;%PATH%
  - bundle install

build: off

test_script:
  # Tests use real git commands
  - git config --global user.email "danger@example.com"
  - git config --global user.name "Danger McShane"
  - bundle exec rake specs
```

**Comment by orta** [comment]
It _may_ be the wrong path, but there's an awful lot of error messages right next to the failing tests ;)

**Comment by sleekybadger** [comment]
Oh, my best wishes to you 🎉 🎉 🎉 

Thank you I will try new config at the evening. I'm a little bit confused, cause this changes not related to git.

**Comment by sleekybadger** [comment]
this did the trick :sparkles:

**Comment by orta** [comment]
Perfect - thanks, it's a setup we have on all other CI providers but not this one 👍

**Comment by sleekybadger** [comment]
@orta with pleasure;) sleekybadger@gmail.com

**Pull request merged**
