### PR TITLE
Removing `--all` option for `git merge-base`

### PR DESCRIPTION
**Pull request by tbrand**
A patch for fixing
- https://github.com/danger/danger/issues/965
- https://github.com/danger/danger/issues/904
- https://github.com/danger/danger/issues/966

I've tried this patch in my environment and it solves all of the crashes.

### CODE REVIEW

**Comment by orta** [comment]
I'm really wary of making any changes around this (the code churn is really high on this bit of code because there are so many different CI/git setups) can you make this a CLI option instead?

**Comment by raymondhoagland** [comment]
@orta not sure I understand why this would make sense as a CLI option.  Is there an expected benefit to using the `--all` flag?  

The current code only handles if there is one response, but asks for multiple.  That seems like a bug that should be addressed for everyone not made optional unless there is a use case where we'd prefer to get multiple responses and fail for some reason.  If that's the case then maybe documentation/comments are needed to explain why that's desired.

**Comment by orta** [comment]
It's more that I don't entirely have all of danger ruby in my head anymore, and so I value codebase stability. I re-read the history around these changes, and this is probably fine to go 👍

**Comment by orta** [comment]
Shipped as 5.5.11

**Pull request merged**
