### PR TITLE
[Dangerfile] Dont call singleton_class? on 2.0

### LINKED ISSUE #240: Class.singleton_class? is not available on ruby 2.0.0
See https://travis-ci.org/realm/jazzy/builds/134747812

```sh
The command "bundle exec rake spec" exited with 0.
3.45s$ bundle exec danger
bundler: failed to load command: danger (/Users/travis/build/realm/jazzy/vendor/bundle/ruby/2.0.0/bin/danger)
NoMethodError: undefined method `singleton_class?' for Danger::DangerfileGitHubPlugin:Class
  /Users/travis/build/realm/jazzy/vendor/bundle/ruby/2.0.0/gems/danger-0.8.0/lib/danger/danger_core/dangerfile.rb:87:in `block in refresh_plugins'
  /Users/travis/build/realm/jazzy/vendor/bundle/ruby/2.0.0/gems/danger-0.8.0/lib/danger/danger_core/dangerfile.rb:86:in `each'
  /Users/travis/build/realm/jazzy/vendor/bundle/ruby/2.0.0/gems/danger-0.8.0/lib/danger/danger_core/dangerfile.rb:86:in `refresh_plugins'
  /Users/travis/build/realm/jazzy/vendor/bundle/ruby/2.0.0/gems/danger-0.8.0/lib/danger/danger_core/dangerfile.rb:79:in `initialize'
  /Users/travis/build/realm/jazzy/vendor/bundle/ruby/2.0.0/gems/danger-0.8.0/lib/danger/commands/runner.rb:38:in `new'
  /Users/travis/build/realm/jazzy/vendor/bundle/ruby/2.0.0/gems/danger-0.8.0/lib/danger/commands/runner.rb:38:in `run'
  /Users/travis/build/realm/jazzy/vendor/bundle/ruby/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
  /Users/travis/build/realm/jazzy/vendor/bundle/ruby/2.0.0/gems/danger-0.8.0/bin/danger:5:in `<top (required)>'
  /Users/travis/build/realm/jazzy/vendor/bundle/ruby/2.0.0/bin/danger:23:in `load'
  /Users/travis/build/realm/jazzy/vendor/bundle/ruby/2.0.0/bin/danger:23:in `<top (required)>'

```

### PR DESCRIPTION
**Pull request by segiddins**
Closes #240

### CODE REVIEW

**Comment by orta** [comment]
```
  1) Danger::Dangerfile printing verbose metadata creates a table from a selection of external plugins DSL attributes info
     Failure/Error: value = plugin.send(method)
     
     RuntimeError:
       You have to provide a message
     # ./danger_plugins/protect_files.rb:4:in `protect_files'
```

Interesting, this shouldn't happen, the rarity of protect_files should be greater than 0

**Comment by orta** [comment]
e.g

```ruby
        methods = plugin_hash[:methods].reject { |name| plugin.method(name).arity != 0 }

        methods.map do |method|
          value = plugin.send(method)
```

would switching this to `select` on `arty == 0` help?

**Comment by orta** [comment]
Oh - I see, so, in theory `    def protect_files(path: nil, message: nil, fail_build: true)` could have an arity of 0 cause of the default values

**Comment by orta** [comment]
Thanks, I'll ship it after this greens 🍏

**Comment by segiddins** [comment]
Should Danger have printed the changelog warning the second time here?

**Comment by orta** [comment]
Nope, looks like a bug, weird, that part of the codebase is pretty well tested

**Pull request merged**
