### PR TITLE
Support for raw markdown as well

### PR DESCRIPTION
**Pull request by KrauseFx**
I'm working on a better fastlane / danger integration. I need a way to add markdown comments to a PR, to show inline links and in general have more control over the design and layout.

The UI is simple, you just use `markdown("### h3 here")` to print markdown below the table or as the only content.

By supporting raw markdown comments, we don't lock our users in our tables. Assume someone wants a little more customization, they can just use the `markdown` method, without having to fork and maintain `danger`.

What do you all think? I'll add some more tests and docs :+1:

### CODE REVIEW

**Comment by marcelofabri** [comment]
I like this idea :sparkles:

**Comment by KrauseFx** [comment]
Waiting for an ok from @orta :+1:

**Comment by orta** [comment]
Yep, I like this :+1:

**Comment by jeroenvisser101** [comment]
This is cool! 👍

**Comment by KrauseFx** [comment]
Alright, thanks everybody, I'll add some more tests and docs :+1:

**Comment by KrauseFx** [comment]
All green, here we go :rocket:

**Comment by jeroenvisser101** [comment]
🎉

**Pull request merged**
