### PR TITLE
Add github enterprise support to CodeBuild

### PR DESCRIPTION
**Pull request by naari3**
- Add spec test
- Change to allow source repo url which not ended with '.git'
  - it is valiable on code build
- Change to be able to handle host which likes github enterprise

### CODE REVIEW

**Comment by orta** [comment]
Looks like this is causing a real failure: 

```
rspec ./spec/lib/danger/danger_core/plugins/dangerfile_gitlab_plugin_spec.rb:98 # Danger::DangerfileGitLabPlugin repository_web_url should request the project
```

**Comment by naari3** [comment]
hmm...seems to occur in current master...
Maybe this PR is not related.

```
Failures:

  1) Danger::DangerfileGitLabPlugin repository_web_url should request the project
     Failure/Error: project = Gitlab::ObjectifiedHash.new({:web_url => "https://gitlab.com/k0nserv/danger-test"})

     NameError:
       uninitialized constant Gitlab
     # ./spec/lib/danger/danger_core/plugins/dangerfile_gitlab_plugin_spec.rb:104:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:125:in `block (2 levels) in with_git_repo'
     # ./spec/spec_helper.rb:113:in `chdir'
     # ./spec/spec_helper.rb:113:in `block in with_git_repo'
     # ./spec/spec_helper.rb:112:in `with_git_repo'
     # ./spec/lib/danger/danger_core/plugins/dangerfile_gitlab_plugin_spec.rb:99:in `block (3 levels) in <top (required)>'
```

I created another PR #1171 and please review if you like

**Comment by danger-public** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Tests were not updated</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by orta** [comment]
Ace, thanks @naari3

**Pull request merged**
