### PR TITLE
Fix danger_id and new_comment flag not working

### PR DESCRIPTION
**Pull request by 4oby**
Fix when running `danger --new-comment --danger_id="id" pr <link>`
the flags `--new-comment` and `--danger_id` where set to `nil`

### CODE REVIEW

**Comment by orta** [comment]
Danger `pr` doesn't actually post comments - it's for running your local Dangerfile against a PR and shows the output in your terminal. You want `danger` or `danger run` for commenting on a PR.

**Comment by orta** [comment]
Or does it just not work without those?

**Comment by 4oby** [comment]
It works, but does not post, `danger pr` is easier, IMO, to hook into our current Jenkins setup.

**Comment by orta** [comment]
You should be using `danger` or `danger run` for that. 

Adding the ability to run danger from CI via `danger pr` will make it more confusing to understand what commands to use. Can you explain why it's easier to use Danger PR?

**Comment by 4oby** [comment]
Jenkins is setup to run on a detached head, so any attempts to run `danger` ends in "not a pr" message.

**Comment by nikolaykasyanov** [comment]
@4oby this message could mean that something important is missing in the environment (PR identifier, for example).

I'm using Danger on Jenkins with detached head builds, haven't had such message with properly configured environment.

**Comment by orta** [comment]
Yeah, this does sound more like your Jenkins setup needs the env vars I think. The check looks [like this](https://github.com/danger/danger/blob/master/lib/danger/ci_source/jenkins.rb#L74).

**Comment by mihai8804858** [comment]
We finally configured danger to run on our Jenkins. The problem was that `"ghprbPullId"` environment variable was not exported. I saw that this variable is exported automatically by `GitHub pull request builder plugin`, but we're not using this plugin because it's not compatible with our job's configuration, so we manually export this environment before running danger. And it works!
Thank you @orta and @nikolaykasyanov for your help.
@4oby I think we can close this PR.

**Comment by orta** [comment]
👍

**Pull request closed without merging**
