### PR TITLE
Migrate to CircleCI 2.0

### PR DESCRIPTION
**Pull request by serima**
Migrate to CircleCI 2.0.

In the previous configuration of CircleCI, the version of ruby was specified as 2.1.3, but this time I am using 2.1 ruby docker image.
The reason is that, as a result of testing the build at hand several times, ruby version 2.1.3 image does not cache hit almost every time.

https://discuss.circleci.com/t/cache-docker-image/12790

Currently, `ruby 2.1.10 p492 (2016-04-01 revision 54464)` is used in CircleCI 2.0.

### CODE REVIEW

**Comment by orta** [comment]
Ah yeah, I'm chill on the Ruby version - I use 2.1.3 because I liked that version of ruby a few years ago, and I enjoy the consistency, which ever version works is fine for me

**Comment by orta** [comment]
Thanks @serima - if you're happy, I'm good to merge?

**Comment by serima** [comment]
@orta Thanks! Yeah I'm happy. Good to merge 🚀

**Comment by orta** [comment]
rockin'

Want to join the org?

**Comment by serima** [comment]
@orta yea, I definitely want to join 😄

**Comment by orta** [comment]
Sent 👍

**Pull request merged**
