### PR TITLE
Remove GNU utilities

### PR DESCRIPTION
**Pull request by henriwatson**
This pull request addresses #331.

After applying this PR, Danger passes all tests on Windows.

### CODE REVIEW

**Comment by orta** [comment]
Nice one, looks good to me 👍

**Comment by orta** [comment]
also, I've invited you to the org, as a part of [Moya Community Continuity](https://github.com/Moya/contributors) - you're welcome to participate in PRs and help out at a level that works for you, you can also not - it's no problem.

**Comment by henriwatson** [comment]
Great! Thank you. (:

**Comment by KrauseFx** [comment]
This is great, thanks @henriwatson 👍

**Pull request merged**
