### PR TITLE
Updated README to mention notifications require markdown

### LINKED ISSUE #317: @mentions in PR
I have a rule that triggers an @mention of a group:

screenshot 2016-07-08 21 08 55

Note that the group is not bolded or link'ed. It does not appear to be triggering a notification. 

The `Dangerfile` code is:

```Ruby
frontend_changes = !modified_files.grep(/(frontend|app\/assets\/javascripts)/).empty?
  
if frontend_changes
  message("The frontend has been changed ... ping @kickstarter/frontend")
end
```

Am I doing something wrong here?

### PR DESCRIPTION
**Pull request by jamtur01**
Fixes #317

You cannot trigger PR notifications within the HTML table. You must use a `markdown` message below the table.

#trivial

### CODE REVIEW

**Comment by orta** [comment]
Oh yeah - there was _literally_ a mention of this in the README with bad advice! Thanks

**Comment by orta** [comment]
Thanks! ( want in on the org? ( no pressure, we conform to the [Moya contributor guidelines](https://github.com/Moya/contributors) )

**Comment by jamtur01** [comment]
@orta Sure. Happy to help. Likely to be doc updates largely, as hideously time poor.

**Comment by orta** [comment]
Zero expectations, but at least now you have some control over your destiny

**Pull request merged**
