### PR TITLE
Adds a run on github actions to Danger

### PR DESCRIPTION
**Pull request by orta**
This should add a GitHub Action CI run for Danger on PRs

### CODE REVIEW

**Comment by danger-public** [comment]
## Danger has errored
[!] Invalid `Dangerfile` file: No JUnit file was found at junit-results.xml
```
 #  from Dangerfile:58
 #  -------------------------------------------
 #  
 >  junit.parse "junit-results.xml"
 #  junit.headers = %i(file name)
 #  -------------------------------------------
```

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by orta** [comment]
Looks fine

Screen Shot 2020-04-06 at 5 07 32 PM

Screen Shot 2020-04-06 at 5 07 25 PM

**Comment by danger-public** [comment]
## Danger has errored
[!] Invalid `Dangerfile` file: syntax error, unexpected end-of-input
```
 #  from Dangerfile:62
 #  -------------------------------------------
 #    junit.report
 >  end
 #  -------------------------------------------
```

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by orta** [comment]
Merge on green

**Pull request merged**
