### PR TITLE
use claide-plugins to add plugin management commands to danger

### PR DESCRIPTION
**Pull request by dbgrandi**
This depends on https://github.com/dbgrandi/claide-plugins/pull/1 (and probably the publishing of that gem)

This would add:

`danger plugin create`
Uses the template at https://github.com/danger/danger-plugin-template to create a new danger plugin

`danger plugin list`
Pull from a JSON file to list all known danger plugins (I think @orta has been thinking about how to publish these automatically from rubygems updates)

`danger plugin search <foo>`
Pattern matches from the list of available plugins (uses that same JSON file)

It would also give us a place to add additional subcommands for linting/testing/documenting new plugins that people are making.

### CODE REVIEW

**Comment by KrauseFx** [comment]
You might want to check out https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/plugins/plugin_search.rb in combination with https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/plugins/plugin_fetcher.rb, I built basically the same thing for `fastlane` 👍

**Comment by orta** [comment]
Yeah, we discussed the idea of using Rubygems for the search, but ended up going with whitelisting - mainly because right now we're advising people use plugins as a way of sharing code. This would mean there'd be quite a lot of "only useful to me" plugins.

https://github.com/danger/danger/issues/249 might mitigate that somewhat - but I think it's enough to not warrant it

**Comment by dbgrandi** [comment]
1755y3

**Comment by orta** [comment]
This looks good to go on green to me 👍

**Pull request merged**
