### PR TITLE
Add `verify_ssl` argument to skip ssl verification

### PR DESCRIPTION
**Pull request by nikhilsh**
- Add tests for verify ssl
- Add no_proxy_fix gem to fix issue in Ruby 2.4.0/2.4.1

As discussed in https://github.com/danger/danger/issues/830

Done with the help of @winston

### CODE REVIEW

**Comment by JuanitoFatas** [comment]
awesome!

only one tiny offense:

```
Offenses:
lib/danger/commands/pr.rb:78:45: C: Use the new Ruby 1.9 hash syntax.
        config.connection_options[:ssl] = { :verify => @verify_ssl }
                                            ^^^^^^^^^^
81 files inspected, 1 offense detected
```

**Comment by orta** [comment]
Yep - this looks 👍

**Comment by orta** [comment]
Lets do it, I'll ship a release

**Comment by miccheng** [comment]
Thank u @JuanitoFatas!!

**Pull request merged**
