### PR TITLE
Add missing require statements to CI subclasses

### PR DESCRIPTION
**Pull request by JuanitoFatas**
* [danger/danger #1484 - CircleCI](https://circleci.com/gh/danger/danger/1484?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)
* [Job #2334.1 - danger/danger - Travis CI](https://travis-ci.org/danger/danger/jobs/160656761)
* [Job #2339.3 - danger/danger - Travis CI](https://travis-ci.org/danger/danger/jobs/160682667)
* [Job #2337.2 - danger/danger - Travis CI](https://travis-ci.org/danger/danger/jobs/160680408)

They all cannot find their `supported_request_sources`, I think they need to require files they need in order to reference them.

#trivial

### CODE REVIEW

**Comment by orta** [comment]
Nice one - yeah - this looks like it 👯

**Comment by JuanitoFatas** [comment]
> Nice one - yeah - this looks like it 👯

:bow: I am still verifying if this really fixes it 😅

**Comment by orta** [comment]
🎉

**Comment by dblock** [comment]
FYI this fixes downstream plugins' build, maybe you want to release it?

**Comment by orta** [comment]
I think this got shipped a week ago, we've had 3.3.1 and 3.3.2 since then

**Pull request merged**
