### PR TITLE
Fail gracefully, instead of throwing stack traces #trivial

### LINKED ISSUE #116: danger local crashing due to missing repo_slug
Haven't had time to look into this yet, I get the following error:

```
~/Developer/fastlane/danger/bin/danger local --verbose

Danger local requires a repository hosted on github.
Not a Pull Request - skipping `danger` run
/Users/fkrause/Developer/fastlane/danger/lib/danger/commands/local.rb:25:in `run': undefined method `repo_slug' for nil:NilClass (NoMethodError)
	from /Users/fkrause/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/claide-1.0.0.beta.1/lib/claide/command.rb:312:in `run'
	from /Users/fkrause/Developer/fastlane/danger/bin/danger:5:in `<main>'
```

### PR DESCRIPTION
**Pull request by jeroenvisser101**
Fixes #116.

### CODE REVIEW

**Comment by orta** [comment]
Looks good, happy to merge w/ CHANGELOG

**Comment by orta** [comment]
ah, maybe this is a trivial one

**Comment by orta** [comment]
:+1:

**Comment by jeroenvisser101** [comment]
@orta – I was working on some tests, but it's kinda hard to do, since it's a shell command, and does things like `puts` and `exit`

**Comment by orta** [comment]
yeah, still struggling to figure out the right way to test "in command" space

**Comment by jeroenvisser101** [comment]
I guess we could stub/mock 'puts' and 'exit' inside the `Command` class, so that they not yield anything, but I'm not sure if that'd help much.

**Comment by orta** [comment]
In CocoaPods we use a UI abstraction, which turned into this gem: https://github.com/CocoaPods/Cork

I'm happy for us to start using it? But Danger would need to be the principal owner of the project, as right now CocoaPods doesn't use it

**Comment by jeroenvisser101** [comment]
Hmmm, looks promising, we could do that!

**Pull request merged**
