### PR TITLE
Fix implementation of bsearch in GitlabCI#determine_merge_request_id

### PR DESCRIPTION
**Pull request by dvlprliu**
This is a very simple PR, just change the `==` operator to `>=` according to [ruby doc](https://ruby-doc.org/core-2.2.0/Array.html#method-i-bsearch)

### CODE REVIEW

**Comment by dvlprliu** [comment]
@DangerCI Of course, would love to. 😃

**Comment by orta** [comment]
👍 Alright - I've sent the invite, and this looks good to me

**Comment by nikolaykasyanov** [comment]
I'm not sure this PR is the reason but Danger posts comments to the wrong Merge Request.

**Comment by nikolaykasyanov** [comment]
I'm not even sure whether it's safe to use bsearch on this array. It's definitely sorted but not by `mr.sha`. Am I missing something?

**Comment by sleekybadger** [comment]
@nikolaykasyanov @orta I'm pretty sure that this is a reason, cause `sha` and `base_commit` are string and in ruby:

```
'dcb' > 'abc'
 => true
'abc' >= 'dcb'
 => false
```
We are not sorting array here, this block returns first merge request, which has same sha as base commit

**Comment by orta** [comment]
good debugging 👍

**Comment by nikolaykasyanov** [comment]
What about replacing bsearch with stupid linear search? I can make a PR.

**Comment by orta** [comment]
Seems fine to me, can't imagine it's a massive list to go through 👍

**Comment by sleekybadger** [comment]
Not sure that this is necessary, cause commit sha is unique, so we can simply revert this pr

**Comment by nikolaykasyanov** [comment]
@sleekybadger I'm still confused and probably missing something. Doesn't using `bsearch` on an array assumes that it's sorted by the key we use in bsearch's block?

**Comment by sleekybadger** [comment]
@nikolaykasyanov yeah, you're right. We can use `Array.index` which is leaner.

```
merge_request = merge_requests.auto_paginate.index do |mr|
  mr.sha == base_commit
end
  
merge_request.nil? ? 0 : merge_request.iid
```

**Comment by nikolaykasyanov** [comment]
@sleekybadger @orta thanks for discussion & making it quick!

**Pull request merged**
