### PR TITLE
Message pluralisation #trivial

### LINKED ISSUE #177: Pluralise error messages at the end of a build when cannot set PR status
From this build: https://travis-ci.org/CocoaPods/CocoaPods/jobs/123843848

`Found 1 error(s) and I don't have write access to the PR set a PR status.`

### PR DESCRIPTION
**Pull request by jeroenvisser101**
Fixes #177

### CODE REVIEW

**Comment by KrauseFx** [comment]
I think we have this code on multiple parts already. Could we move this to the String class similar to what Rails does, and have a `danger_pluralize` method or similar?

**Comment by jeroenvisser101** [comment]
@KrauseFx sure we can, I'll update it tonight, heading home now!

**Comment by jeroenvisser101** [comment]
Actually, inflection in ActiveSupport is somewhat more complex than we need:

https://github.com/rails/rails/blob/861b70e92f4a1fc0e465ffcf2ee62680519c8f6f/activesupport/lib/active_support/inflector/methods.rb#L30

We could maybe create a helper method `pluralize(count, '1 warning', '%d warnings')` and use that, but I think that would maybe be a bit too much.

Another option is having a method that just adds a 's' when count doesn't equal 1, which would be correct in most cases.

**Comment by KrauseFx** [comment]
Sorry, that's not what I meant. 

I mean something like
```ruby
class String
  def danger_plura_le_name(count)
     self + "s" # or whatever here
  end
end
```

**Comment by jeroenvisser101** [comment]
Ah, I misunderstood, I'll do that :)

**Comment by jeroenvisser101** [comment]
@KrauseFx I edited it a little, can you check if this is what you meant?

**Comment by orta** [comment]
This is what I think he was referring to now 👍

**Comment by jeroenvisser101** [comment]
Cool! :)

**Comment by KrauseFx** [comment]
Perfect, thanks for updating! 👍

**Comment by jeroenvisser101** [comment]
Happy to do so :)

**Pull request merged**
