### PR TITLE
Added new modified_files.include?("pattern*") method

### PR DESCRIPTION
**Pull request by KrauseFx**
Fixes https://github.com/danger/danger/issues/82

### CODE REVIEW

**Comment by orta** [comment]
nice work

**Comment by KrauseFx** [comment]
Build works, however fails because of Circle issues from today, ready to merge @orta?

**Comment by orta** [comment]
Yep, looks good to me, will make an issue abut the map function too :+1:

**Comment by KrauseFx** [comment]
Oh yeah :rocket:

**Pull request merged**
