### PR TITLE
[WIP] Add a plugins manager based off CocoaPods'

### LINKED ISSUE #131: Danger Plugins as Gems
They should have two major abilities:

- Provide DSL attributes
- Support providing it's own linting, if requested by a Dangerfile, with the current context variables provided by the system.

What does this look like?

```  Ruby
# Gemfile
gem 'danger'
gem 'danger-jekyll'
```

```  Ruby
# Dangerfile
[... usual stuff specific to a project]

# `danger-jekyll` exposes a DSL attribute for `validate_prose`
validate_prose "_site/pages/*.md"

# runs any plugin linting
plugin 'jekyll', { :project => "Artsy" }
```

This isn't too new, CocoaPods does all this stuff, and we spend a long time figuring out how this should work.

TODOs for this issue to be done:

- [ ] Adds plugin DSL attributes
- [x] Adds plugin linter hooks, with optional hash support
- [ ] Documentation
- [ ] `danger plugin create` - generates a stubbed plugin, see [cocoapods-plugins](https://github.com/CocoaPods/cocoapods-plugins/blob/master/lib/pod/command/plugins/create.rb) - this can be expanded upon in a different issue if needed.

### PR DESCRIPTION
**Pull request by orta**
Fixes #131

### CODE REVIEW

**Comment by jeroenvisser101** [comment]
Should we add documentation on how to do this in the README/wiki and have a tutorial on how to write plugins? Also, should we move [`protected_files.rb`](https://github.com/danger/danger/blob/master/lib/danger/plugins/protect_files.rb) into a plugin too?

**Comment by orta** [comment]
I think we should provide a lot of the core git diff DSL tools in Danger, there's a lot more to go on this PR, no worries yet

**Comment by jeroenvisser101** [comment]
Alright! I'll check back on this later, let me know if I can help on this/what your plans are :)

**Comment by segiddins** [comment]
This should use CLAide instead of copy-pasting code

**Pull request closed without merging**
