### PR TITLE
Allow two slashes in URL slug

### PR DESCRIPTION
**Pull request by dstranz**
Fix for issue described in #968 - correct slug detection for repository with following url:
`https://git.myhost.com/ORGANISATION/TEAM/REPOSITORY_NAME` allowed by GitLab.

I cannot simply add new regexp group `(/[^/]+){1,2}` because then it will also match part of domain name, so I added `://[^/]+/` at the beginning to catch only url path.

### CODE REVIEW

**Comment by dstranz** [comment]
@orta should I update documentation? What does Core Docs Error mean?

**Comment by orta** [comment]
Looks like something inside [the dangerfile](https://travis-ci.org/danger/danger/jobs/405270247#L2055-L2066) is failing, causing a knock-on effect:

```
2.27s$ bundle exec danger --verbose
/home/travis/.rvm/gems/ruby-2.0.0-p648/bin/bundle:23:in `load': cannot load such file -- /home/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/gems/2.0.0/gems/bundler-1.16.3/exe/bundle (LoadError)
	from /home/travis/.rvm/gems/ruby-2.0.0-p648/bin/bundle:23:in `<main>'
	from /home/travis/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:24:in `eval'
	from /home/travis/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:24:in `<main>'
/home/travis/.rvm/gems/ruby-2.0.0-p648/bin/bundle:23:in `load': cannot load such file -- /home/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/gems/2.0.0/gems/bundler-1.16.3/exe/bundle (LoadError)
	from /home/travis/.rvm/gems/ruby-2.0.0-p648/bin/bundle:23:in `<main>'
	from /home/travis/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:24:in `eval'
	from /home/travis/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:24:in `<main>'
Danger has failed this build. 
Found 1 error.
```

**Comment by orta** [comment]
*waves hands* magic

orrrr.... flakey tests.

**Comment by toineheuvelmans** [comment]
Actually I'm still struggling with this issue, as the regex used in [this file](https://github.com/danger/danger/blob/master/lib/danger/ci_source/bitrise.rb) still only captures a single slash. Would that involve a similar adjustment to the regex?

**Comment by dstranz** [comment]
Yes, I also has this problem :/ I have ready PR with another fix - will submit it in a minute.

**Pull request merged**
