### PR TITLE
[WIP] - add gitlab support + SPLIT out APISources

### PR DESCRIPTION
**Pull request by hjanuschka**
hello

i like the idea of danger - and i want to have it - but since we are using gitlab.
this is an unfinished WIP PR - that try's to split out the API source logic
and implement a `gitlab.rb` doing the stuff using 'gitlab' gem.

let me know what you think about it, right now its broken, since i am still fighting with the gitlab api.

at the end there needs to be a little webapp, that receives the `merge_request` hook from gitlab.
wich then does the danger thing, as of now the CI in gitlab is not able to detect if it is inside a merge-request.

lg

### CODE REVIEW

**Comment by orta** [comment]
Great! This looks like a solid foundation IMO

**Comment by hjanuschka** [comment]
a few fixme's to go, but i am already able to run danger against a `--mirror` cloned gitlab repo.

**Comment by orta** [comment]
A warning, I just merged a bunch of PRs, it may be worth rebasing early next time you look at this

**Comment by hjanuschka** [comment]
thx - rebased to current master ;)

**Comment by k0nserv** [comment]
@hjanuschka what's the status of this?

**Comment by hjanuschka** [comment]
waiting for a gitlab api mr before incan continue
-- 
Helmut Januschka
Sent with Airmail

**Comment by orta** [comment]
I don't know GitLab, but I imagine the baseline APIs needed would be: A Merge Request JSON summary, and the ability to auth & comment on a Merge Request - the status API can be skipped IMO.

**Comment by hjanuschka** [comment]
already works - just waiting for this one to be merged 

https://github.com/NARKOZ/gitlab/pull/178
-- 
Helmut Januschka
Sent with Airmail

**Comment by orta** [comment]
Amazing!

**Comment by KrauseFx** [comment]
I see https://github.com/NARKOZ/gitlab/pull/178 got merged already, could you fix the merge conflicts? :+1:

**Comment by hjanuschka** [comment]
* rebased current master

sorry i still haven't found the time to finish this, mostly coz i have no idea how to cleanly solve the "trigger" problem. as gitlab-ci doesnt trigger a build on PR changes. only sends a json payload, and i therefore need to find a smooth way todo the danger stuff.

**Comment by jk** [comment]
@hjanuschka I just tested it, new pushs to the branch (which I specified as source of the MR) trigger various `X-Gitlab-Event: Build Hook` web hook triggers if you enabled web hooks for build events. But you're right, there is no reference that this gitlab-ci build is building a commit which is related to a MR, albeit the MR page references the new commit's build run on top of the page as well as down in the comments.

Perhaps we should open an issue over on gitlab-ce's issue tracker? Did you already did this? I'm happily create one, if not.

**Comment by jk** [comment]
Since I did not find an issue on gitlab's issue tracker I just created one: https://gitlab.com/gitlab-org/gitlab-ce/issues/14654

**Comment by hjanuschka** [comment]
thx for the issue on gitlab side.

right now this is the state, of this WIP PR.


 * clone your gitlab repo.
 * create branch, and create mr on gitlab (get mr-id)
 * get gitlab access token.
 * get project id
 * set following - envs..:
  - `DANGER_GITLAB_PRIVATE_TOKEN=<PRIV_TOKEN>`
  - `DANGER_GITLAB_ENDPOINT=http://gitlab.com/api/v3`
  - `GITLAB_MR_ID=123`
  - `GITLAB_PROJECT_ID=1234`

 * run danger in the cloned repo.


it should work from this place, and danger should comment, and/or update the comment on the MR.



its pretty far from this. we only need to automate the env-setting (according the json we receive on mr-events.)


plan 1:
  - have a little web-app (node,go or whatever)
  - receive the json payload
  - clone the repo
  - set the envs
  - run danger

  * pro
    - should be ease to build
 * cons
   - a another services needs to be integrated in ops-workflow
   - waste of space
   - cleanup code and so on
    - web app requires deploy key


plan 2:
  - have a little web-app (node,go or whatever)
  - receive the json payload
  - tag the repo  (via api) - like `danger_<PROJECT_ID>_<MR_ID>-<AUTO_INCR_INDEX>`
  - handle the danger in the `.gitlab-ci.yml` with a `only: danger_.*`

  * pro:
    - cloning and cleanup is handled by gitlab-ci as usual
    - artifacts / caches / docker and so on
 
 * cons:
    - regex on branch name isn't perfect, maybe a place for errors.
    - web app requires api-token

**Comment by k0nserv** [comment]
https://gitlab.com/gitlab-org/gitlab-ce/issues/14654#note_12065382

**Comment by k0nserv** [comment]
[They claim this is already being done](https://gitlab.com/gitlab-org/gitlab-ce/issues/14654#note_12171529). @hjanuschka could you drop a line in the issue explaining it further?

**Comment by k0nserv** [comment]
So with the merge of #221 this needs to be updated to fit that structure

**Comment by k0nserv** [comment]
I've adopted some of this PR in https://github.com/k0nserv/danger/tree/gitlab 

Asked Gitlab about adding a `GITLAB_MERGE_REQUEST` environment variable in builds similar to `TRAVIS_PULL_REQUEST` and `CI_PULL_REQUEST`.

**Comment by connorshea** [comment]
@k0nserv I'll gladly support you internally, would love to see support for GitLab in Danger :) We may even use it for GitLab CE :D

[14654](https://gitlab.com/gitlab-org/gitlab-ce/issues/14654) doesn't seem to be about adding a GITLAB_MERGE_REQUEST environmental variable, is there an issue open for it that you know of/would you like to open one?

**Comment by hjanuschka** [comment]
@k0nserv  sorry been busy, had no time to work on the danger-gitlab stuff, thx for stepping in!! looking forward to your PR

@connorshea  thx for your help - i really would love to have danger integrated into our gitlab-ci workflows

**Comment by connorshea** [comment]
@k0nserv @hjanuschka also, the `gitlab` gem is a community-created gem. While there is a current maintainer, he wasn't given the ability to push updates to RubyGems.

We may have to contact RubyGems support and try to get access to the gem ourselves so we can update it, or we'll have to work with the current maintainer to release the gem under a different name. Not sure which is preferable.

**Comment by connorshea** [comment]
Oh, and to be clear we have tried getting into contact with Narkoz, but he seems to have essentially disappeared.

**Comment by orta** [comment]
( As someone who runs a dependency manager, sending a quick email here explaining the problem should get that fixed pretty quickly 👍 )

**Comment by k0nserv** [comment]
You think Rubygems would transfer ownership of the gem? That seems highly unlikely IMO. As a RubyGems user I sure hope they don't do that. Maybe they can at least issue a release, but we can't tag in git

**Comment by orta** [comment]
> You think Rubygems would transfer ownership of the gem?

Yeah, we do that all the time at CocoaPods. People lose access to emails, or stop working at a place all the time.

**Comment by k0nserv** [comment]
> Yeah, we do that all the time at CocoaPods. People lose access to emails, or stop working at a place all the time.


Indeed, but in this case we are talking about transferring ownership from someone without their confirmation. Seems like a more drastic thing

**Comment by k0nserv** [comment]
Oh sorry, he wasn't given the ability to push to rubygems? So `gitlab` is essentially ownerless then?

@connorshea You are indeed correct that Gitlab CI does not currently expose the correct environment variables in CI. I've raised it with the in the linked question. The other open question is being able to trigger CI on new/edit comments and updates to the MR itself. However do keep in mind that GitLab can still be used with our forms of CI, we use Drone + GitLab at Skyscanner for example

**Comment by k0nserv** [comment]
Also I've emaild Narkoz and we'll see if he finds the time

**Comment by k0nserv** [comment]
Opened #299 for this and I suggest we move the conversation there

**Comment by orta** [comment]
Aye, closing, @hjanuschka thanks for getting this started 👯 

All conversation is welcome to move over to #299

**Comment by k0nserv** [comment]
Idd thanks @hjanuschka your implementation has been very helpful in the implementation of #299 and the work on the gitlab gem has helped greatly too

**Pull request closed without merging**
