### PR TITLE
fix nil repo_slug when repo name contains dot

### PR DESCRIPTION
**Pull request by johnlinvc**
## Purpose

Fix Issue when GitHub repo's name contains dot.
`repo_slug` became `nil` when the repo's name has a dot in it. (e.g.  johnlinvc/test-2.0)

## Changes

Handle repo name with dot correctly in `CISource::Jenkins#initialize`

### CODE REVIEW

**Comment by johnlinvc** [comment]
The CI tests are failing for the reason in #738 .
I'll rebase again when 738 is merged.

**Comment by orta** [comment]
Awesome, this looks good to me!

**Comment by orta** [comment]
@johnlinvc  I've invited you to the org, as a part of [Moya Community Continuity](https://github.com/Moya/contributors/issues/6) - you're welcome to participate in PRs and help out at a level that works for you.

**Comment by johnlinvc** [comment]
Joined! looking forward to help the community.

**Pull request merged**
