### PR TITLE
Fix run with Azure Pipelines as CI Source and Azure Repos Git as Request Source

### PR DESCRIPTION
**Pull request by damien-danglard**
When running Danger with Azure Pipeline (CI Source), 2 CI Source (Danger::CI subclass) match : `Danger::AzurePipelines` and `Danger::VSTS`, the first is always selected.
The problem is, when I use Azure Repos Git (Request Source), `Danger::RequestSources::VSTS` is in `Danger::VSTS.supported_request_sources` but not in `Danger::AzurePipeline.supported_request_sources`.
So, like it's `Danger::AzurePipelines` selected as default CI Source, an error is throw.

I added a filter in `Danger::AzurePipelines.validates_as_ci?` to return false if Request Source is Azure Repos Git without changing the previous value in other case.
For that I use `BUILD_REPOSITORY_PROVIDER` environment variable defined by Azure Pipeline (see [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#build-variables-devops-services)). The value of this environment variable is "TfsGit" only if Request Provider (Request Source) is Azure Repos Git.

Conclusion: If I use Azure Pipelines with Azure Repos Git, `Danger::AzurePipelines` will not be selected because it does not support `Danger::RequestSources::VSTS`. The selected CI Source will be `Danger::VSTS`, as expected.

PS: I think `Danger::AzurePipelines` and `Danger::VSTS` should be merged because I think they represent the same CI Source (Azure Pipeline is the evolution of VSTS).

### CODE REVIEW

**Comment by danger-public** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Tests were not updated</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by orta** [comment]
Yeah, I think VSTS and Pipelines are now basically the same - it'd be good to get a test for this, but otherwise looks good to me

**Comment by damien-danglard** [comment]
I added tests for Danger::AzurePipelines but I think CI build should be rerun.

**Comment by orta** [comment]
Thanks! Looks good to me

**Pull request merged**
