### PR TITLE
Updates Gemfile

### PR DESCRIPTION
**Pull request by orta**
This should fix the suspicious issues with rubocop, it wasn't in the Gemfile at all.

Also updates some forks now that all PRs are merged.

### CODE REVIEW

**Comment by orta** [comment]
might lock it at a previous version :D

**Comment by orta** [comment]
Ah shame, this would have fixed #738

**Comment by JuanitoFatas** [comment]
Need to rebase after merged #749

**Comment by JuanitoFatas** [comment]
Build is back to green :green_salad:

**Pull request merged**
