### PR TITLE
Bbs network call fix

### PR DESCRIPTION
**Pull request by RishabhTayal**
///////////////////⚡///////////////////

# 🚫 AWESOME A PR!

Fixes a bug where `use_ssl` was called for url without `https://`.

///////////////////⚡///////////////////

### CODE REVIEW

**Comment by orta** [comment]
nice catch on the filename too 👍

**Comment by orta** [comment]
Danger'll raise an issue due to the missing CHANGELOG - other than that, looks good, I'll ship a 5.0.2 from this

**Comment by orta** [comment]
I've merged masted on this branch @RishabhTayal

**Comment by RishabhTayal** [comment]
@DangerCI running @danger-systems on @danger-systems repo. 💯

**Comment by orta** [comment]
This will still need a CHANGELOG entry, then we're good to go

**Comment by orta** [comment]
<£

**Comment by RishabhTayal** [comment]
Added change log

**Comment by orta** [comment]
👍 rock

**Pull request merged**
