### PR TITLE
--new-comment support for Bitbucket

### PR DESCRIPTION
**Pull request by bruno-rocha-movile**
This adds the missing support for —new-comment on Bitbucket

### CODE REVIEW

**Comment by bruno-rocha-movile** [comment]
Seems like there's a rubocop violation from something unrelated to this. Will check it out

``
lib/danger/danger_core/dangerfile.rb:292:7: C: Favor a normal unless-statement over a modifier clause in a multiline statement.
      if ui.title(title) ...
      ^^^^^^^^^^^^^^^^^^
```

**Comment by JuanitoFatas** [comment]
> Seems like there's a code violation from something unrelated to this. Will check it out

I fixed in https://github.com/danger/danger/pull/658. You can rebase and push again, thank you!!! :D

**Comment by bruno-rocha-movile** [comment]
Thank you @JuanitoFatas !

**Comment by orta** [comment]
Awesome, 👍 lets get this in

**Pull request merged**
