### PR TITLE
Update site references to https://danger.systems #trivial

### PR DESCRIPTION
**Pull request by JuanitoFatas**
Since now [our site](https://gitlab.com/danger-systems/danger.systems) is served by GitLab pages with https 🔒 .

### CODE REVIEW

**Comment by orta** [comment]
I'm still a bit hesitant to do this ( _I_ would have to manually re-create the certs every 90 days, which is too short a timeframe for me to say I will do for as long as Danger exists ) so - once this current cert expires, lets see how the redirect is handled. If it works fine, and https links resolve to http - I'm totally cool with doing this 👍  - till then, no point keeping a PR open for ~70 days

**Comment by JuanitoFatas** [comment]
Understood, thanks!

**Comment by ge-fa** [comment]
Hi @orta ,

> I would have to manually re-create the certs every 90 days, which is too short a timeframe for me to say I will do for as long as Danger exists 

Why do you have to re-create the certs manually? Could you elaborate? 

Thanks!

**Comment by orta** [comment]
https://letsencrypt.org only does 90 day certs, and there's no API on GitLab to update the keys - so I would need to download and run certbot again, and upload the new key to GitLab every 90 days

**Comment by ge-fa** [comment]
Alright I see, thanks. I wasn't aware that the URL points to GitLab.

**Comment by orta** [comment]
👍 no worries, it's an interesting constraint

**Pull request closed without merging**
