### PR TITLE
Show full PR body, wrapping at 80 characters #trivial

### PR DESCRIPTION
**Pull request by jeroenvisser101**
This will allow us to see it, without messing up the layout in CI.

Long text for demo:
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

### CODE REVIEW

**Comment by orta** [comment]
screen shot 2016-03-13 at 17 08 59


:tada:

**Comment by jeroenvisser101** [comment]
It does break in the middle of the word, but better than nothing, right? :tada:

**Comment by jeroenvisser101** [comment]
@orta I noticed we use 'key.to_s' everywhere, except for the `pr_body`, should I rename it now?

**Comment by dbgrandi** [comment]
:rocket:

**Pull request merged**
