### PR TITLE
Support for gitlab api v4

### PR DESCRIPTION
**Pull request by sleekybadger**
This should resolve https://github.com/danger/danger/issues/860.

### Summary 
It turned out, that support for v4 doesn't require a lot of changes. But we need to check that everything works as expected, right now we support gitlab for:

- ~~[Bitrise](https://www.bitrise.io)~~ ✅ 
- ~~[Buddybuild](https://www.buddybuild.com)~~ ✅ 
- [Buildkite](https://buildkite.com)
- [Drone](https://github.com/drone/drone)
- [GitLabCI](https://about.gitlab.com/features/gitlab-ci-cd)
- ~~[Jenkins](https://jenkins.io)~~ ✅ 
- [TeamCity](https://www.jetbrains.com/teamcity)

So, I will appreciate any help in testing the remaining ci's 🙏 
You can do this via my danger fork:
```ruby
gem 'danger', github: 'sleekybadger/danger', 
              branch: 'feature/gitlab-api-v4'
```

### P.S.
Right now, if you will use this PR, make sure that you have `gitlab` gem with version 4.2.0. Dependencies in [danger-gitlab](https://github.com/danger/danger-gitlab-gem) not bumped yet

### CODE REVIEW

**Comment by Dimdron** [comment]
Great! For me, it works fine.

**Comment by orta** [comment]
Cool, looks nice and simple

**Comment by sleekybadger** [comment]
@Dimdron Thank you. Can you say on what CI did you test it?

**Comment by Dimdron** [comment]
@sleekybadger I tested it on Jenkins.

**Comment by orta** [comment]
I'm not sure if we'll get any more people testing @k0nserv - do you have access to v4?

**Comment by k0nserv** [comment]
I think we're still on v3 atm. I'll have a look though

**Comment by sleekybadger** [comment]
@orta oh, I think you are right 😃  

I wanna improve a little bit our GitlabCi support according to last comment in [this thread](https://gitlab.com/gitlab-org/gitlab-ce/issues/15280) , fix tests and I think that this can be merged.

**Comment by sleekybadger** [comment]
@orta I think this can be merged. Also we need to merge [danger-gitlab-gem pr](https://github.com/danger/danger-gitlab-gem/pull/4). And I think we should bump `danger` version in `danger-gitlab-gem` too.

**Comment by orta** [comment]
👍 I've triggered an update from master, I might do a full semver release on danger-gitlab for this

If this is green, I'll ship it all. Nice work

**Pull request merged**
