### PR TITLE
Update bundler gem

### PR DESCRIPTION
**Pull request by RDIL**
We should stay up to date on this

### CODE REVIEW

**Comment by orta** [comment]
This won't update the gem, you'd also need to update the lockfile also

**Comment by RDIL** [comment]
I don't see a lockfile anywhere...

**Comment by orta** [comment]
Ah, yeah, looks like we manually install bundler on CIs with a specific version: https://github.com/danger/danger/blob/master/.travis.yml#L16

So if this works that's fine during dev then that might be ok, but we had bundler 2.0 problems for a while

**Comment by RDIL** [comment]
Circle passed, now just travis and appveyor

**Comment by RDIL** [comment]
Travis is green

**Comment by orta** [comment]
👍 - nice one, thanks!

**Pull request merged**
