### PR TITLE
[Plugin] Clean up method_missing #trivial

### PR DESCRIPTION
**Pull request by segiddins**
Object#send will call method_missing internally if necessary

### CODE REVIEW

**Comment by segiddins** [comment]
I don't see why a CHANGELOG entry is necessary?

**Comment by marcelofabri** [comment]
@segiddins You can add #trivial to your PR title to avoid adding a CHANGELOG entry

**Comment by segiddins** [comment]
But then `#trivial` would be part of the default merge commit message, and I don't want that in the commit message

**Comment by marcelofabri** [comment]
I haven't thought about that, sorry for changing it 😬 

Maybe we could check the message as well? cc: @orta

**Comment by orta** [comment]
Yeah - I'm happy to have the trivial check in the body also, not a problem to me 👍🏾
Nice fix

**Comment by orta** [comment]
also, I've invited you to the org, as a part of [Moya Community Continuity](https://github.com/Moya/contributors/issues/6) - you're welcome to participate in PRs and help out at a level that works for you.

**Comment by KrauseFx** [comment]
Looks great 👍

**Pull request merged**
