### PR TITLE
Enforce a changelog entry

### PR DESCRIPTION
**Pull request by orta**
:+1: 

/cc @marcelofabri

### CODE REVIEW

**Comment by KrauseFx** [comment]
:+1:

**Comment by KrauseFx** [comment]
So sad we don't use danger for danger though

**Comment by orta** [comment]
We are:

```
The command "bundle exec rake spec" exited with 0.
1.60s$ bundle exec danger --verbose
Printing message 'Tests were updated / added'
All green. Congrats.

```

I've just not done https://github.com/danger/danger/issues/48 - which will support sending the message, but not doing the status

**Comment by marcelofabri** [comment]
:clap:

**Comment by orta** [comment]
Doing it, man, this CI stuff is complicated ;)

**Pull request merged**
