### PR TITLE
Don't post Dangefile errors as comment on PR when the `DANGER_DO_NOT_POST_INVALID_DANGERFILE_ERROR` env var is set

### PR DESCRIPTION
**Pull request by rymai**
This addresses https://github.com/danger/danger/issues/1352.

### CODE REVIEW

**Comment by orta** [comment]
I'd be open to us filtering the output here with the env vars, I'm not really sold on removing the feature

**Comment by rymai** [comment]
> I'd be open to us filtering the output here with the env vars

Do you merging https://github.com/danger/danger/pull/1353? I think that would address the main issue for us. 👍 Then I'm ok adding an option to not to print errors as comments in PR/MR, if you'd accept that.

**Comment by orta** [comment]
Yeah, I agree it could leak - I'm totally fine with having an option to skip the inline error report 👍🏻

**Comment by rymai** [comment]
@orta Thanks! I changed the PR to not post failure comment when `DANGER_DO_NOT_POST_INVALID_DANGERFILE_ERROR` is set, and keeps the previous behavior otherwise. WDYT?

**Comment by orta** [comment]
I think this is a good answer 👍🏻

**Comment by rymai** [comment]
@orta Would it be possible to have a new `8.4.4.` version released with this fix? 🙏

**Comment by orta** [comment]
Sure

**Comment by orta** [comment]
Shipped

**Pull request merged**
