### PR TITLE
[README] Readd Xcode CI builds

### PR DESCRIPTION
**Pull request by nwest**
Unintentional deletion in https://github.com/danger/danger/pull/199.

### CODE REVIEW

**Comment by jeroenvisser101** [comment]
Travis seems to be acting up...

**Comment by jeroenvisser101** [comment]
@nwest you might want to try creating an empty commit to see if that triggers travis (`git commit --allow-empty`)

**Comment by orta** [comment]
or do an empty amend, and force push, it creates a new sha reference

**Comment by nwest** [comment]
Donezo.

**Comment by jeroenvisser101** [comment]
💥 thanks!

**Pull request merged**
