### PR TITLE
[GitHub] Deduplicate previous violations

### PR DESCRIPTION
**Pull request by segiddins**
#trivial

### CODE REVIEW

**Comment by segiddins** [comment]
@orta how does this look?

**Comment by orta** [comment]
Hrm, IMO, this does look good, I can't tell if it's working, given that it has a dupe in the Danger log above though

**Comment by orta** [comment]
but this one could do with a changelog, think a bunch of people would be glad to see this fix 👯

**Comment by segiddins** [comment]
Yeah, I had trouble testing it and as such didn't feel comfortable adding an entry for it

**Comment by orta** [comment]
Then throw in a `#trivial` and we can see if ti fixes on Danger's PRs

**Comment by segiddins** [comment]
Rebased

**Comment by orta** [comment]
Awesome.

**Pull request merged**
