### PR TITLE
Allow Dangerfile path to be configured

### LINKED ISSUE #219: Dangerfile in subdirectory
Hi there,
I'm trying to integrate Danger with a project of mine, which has this directory layout

```
.
├── .git
└── ios
     └── Dangerfile
```

However, this doesn't work because danger looks for a `.git` directory in the same directory of the Dangerfile.

Is it possible to customize this behavior? Or am I missing something else?

By the way, the reason behind this is that the repo is a monorepo, so the full structure looks something like this:

```
.
├── README.md
├── api
├── ios
└── web
```

And I definitely don't want to "pollute" the root directory with iOS specific files, such as the Dangerfile.

Thanks in advance!

### PR DESCRIPTION
**Pull request by gabro**
Resolves #219 

Add `--dangerfile=<path/to/dangerfile>` option to override the default `Dangerfile` location.

### CODE REVIEW

**Comment by orta** [comment]
Aww - sorry, this got merge-conflicted, any chance you can rebase? Then this look good to go to me - thanks!

**Comment by gabro** [comment]
No problem, I'll do it tomorrow morning!

**Comment by gabro** [comment]
@orta rebased!

**Comment by justMaku** [comment]
Looks fine to me 👍

**Comment by orta** [comment]
@justMaku wanna merge?

**Pull request merged**
