### PR TITLE
Add `commits` for the Git SCM source

### PR DESCRIPTION
**Pull request by segiddins**
Add a commit accessor in the git scm source

### CODE REVIEW

**Comment by segiddins** [comment]
should pass if you restart the build on travis

**Comment by orta** [comment]
Yeah - this looks good 👍

**Comment by segiddins** [comment]
@orta anything else needed to get it merged? I want to add some checks in CocoaPods around there not being any upstream merge commits ;)

**Comment by orta** [comment]
Nope, this is good.

**Pull request merged**
