### PR TITLE
Fixed danger local crash when there are no recent PRs #trivial

### PR DESCRIPTION
**Pull request by KrauseFx**
Show an actual error message if there haven't been any PRs yet

### CODE REVIEW

**Comment by jeroenvisser101** [comment]
@KrauseFx the local command will never work with repositories that use a rebase workflow, should we have a look at that some time? (Should I create a issue?)

**Comment by jeroenvisser101** [comment]
Rest looks good! 👍

**Comment by KrauseFx** [comment]
@jeroenvisser101 in this case it was just a new project I started working on, where I just haven't created a PR yet, but plan on doing so, since it's open source

**Comment by orta** [comment]
👍🏾  good call

**Comment by jeroenvisser101** [comment]
@KrauseFx Alright, but the issue that rebase workflows don't work persist, although it seems that GitHub can see which commit belonged to which branches, we should be able to retrieve that somewhere. I might have a look tonight and see if that's doable. Nevertheless, it's outside the scope of this PR :)

**Comment by orta** [comment]
Cool, yeah, make an issue, that's an interesting problem

**Pull request merged**
