### PR TITLE
Prepare for v3.5.3

### PR DESCRIPTION
**Pull request by JuanitoFatas**
✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ 
///🚫3////5🚫///🚫3/////////⚡//////////////////
✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨

### CODE REVIEW

**Comment by JuanitoFatas** [comment]
https://github.com/danger/danger/blob/2d734e13789a1075bf37feab4157d2f93b125689/.travis.yml#L28-L31 is not working 😓

**Comment by orta** [comment]
Check out the end of the build results for circle, something really odd there - at least it's not greening

**Comment by JuanitoFatas** [comment]
> Yeah, I wonder if the deploy scripts run on a different machine, they do say they run on 1.9.x

Let's merge to see if 099e1c5 is working .

**Comment by orta** [comment]
Fine with me, it's non-critical infrastructure 👍

**Comment by JuanitoFatas** [comment]
> Check out the end of the build results for circle, something really odd there

👉 https://github.com/rspec/rspec-core/issues/2337 Opened an issue on RSpec Core.

**Comment by JuanitoFatas** [comment]
> Check out the end of the build results for circle, something really odd there
> 👉 rspec/rspec-core#2337 Opened an issue on RSpec Core.

It's from https://github.com/orta/rspec_junit_formatter/commit/00c773db3abcea1082243bd568e02d830a5db753, please see https://github.com/orta/rspec_junit_formatter/commit/00c773db3abcea1082243bd568e02d830a5db753#commitcomment-19352389.

**Pull request merged**
