### PR TITLE
Enforce String Literal Styles

### LINKED ISSUE #300: Use consistent quotes
Currently we are specifying 

````
Style/StringLiterals:
  Enabled: false
```

which has resulted in inconsistent string literals all throughout the project. I suggest we enable this cop and update the project to use single quotes for all strings that do not require double quotes(e.g using string interpolation).

cc @orta

### PR DESCRIPTION
**Pull request by DanToml**
closes #300

\c @k0nserv

### CODE REVIEW

**Comment by k0nserv** [comment]
Yay :tada: Thanks, I can't merge though that's a up for  @orta

**Comment by orta** [comment]
Cool for me if green

**Comment by orta** [comment]
looks like some emoji special casing

**Comment by DanToml** [comment]
@orta Also looks like Rubocop has a bug in the string literal cop. Autocorrect works fine, but then fails lint :/. Will special case now and see if I can PR Rubocop.

**Comment by orta** [comment]
cool, makes sense 👍

**Pull request merged**
