### PR TITLE
Sticky false by default

### LINKED ISSUE #482: Proposal Switch messaging's sticky to default to false
When I looked at the Dangerfile for Danger, and Eigen etc, I see a lot of `sticky: false`. 

I think this is now the majority of the messages that I'm sending, and so I think it's time to move it back to the default.

### PR DESCRIPTION
**Pull request by bogren**
Fixes #482. I agree with the issue, most of my dangerfile entries set sticky to false.

### CODE REVIEW

**Comment by orta** [comment]
This is good, @bogren can you add me as a contributor to your Fork, this is going to require a really long  CHANGELOG entry as it's a breaking SemVer major version change, so I want to make it happen with the next one - I don't know for sure when this will get merged - all the code looks 👍  it's cultural now, not technical 

thanks, also do you want in on the org?

**Comment by bogren** [comment]
Sure - I was just about to ask how I would go a head and tag/write my changelog entry. I'll add you to my Fork. Yes please! 👍

**Comment by orta** [comment]
I just wrote this Dangerfile
```
# Sometimes it's a README fix, or something like that - which isn't relevant for
# including in a project's CHANGELOG for example
declared_trivial = github.pr_title.include? '#trivial'

# Make it more obvious that a PR is a work in progress and shouldn't be merged yet
warn('PR is classed as Work in Progress', sticky: false) if !declared_trivial && github.pr_title.include?('[WIP]')

# Warn when there is a big PR
warn('Big PR') if git.lines_of_code > 500

# Don't let testing shortcuts get into master by accident
messaging.fail('fdescribe left in tests', sticky: false) if `grep -r 'fdescribe ' spec/`.length > 1
messaging.fail('fit left in tests', sticky: false) if `grep -r 'fit ' spec/`.length > 1

# Use the rspec failures file from our custom formatter to show failed tests
if File.exist?('rspec.failures')
  errors = File.read('rspec.failures')
  messaging.fail('Specs failed:<br/>' + errors, sticky: false) if errors.length
end
```

I'm looking forwards to merging this

**Comment by orta** [comment]
Alright, I've merged this into #654 - thanks!

**Pull request closed without merging**
