### PR TITLE
Support batch build in AWS codebuild

### PR DESCRIPTION
**Pull request by tomoya-yoshida-dwango**
`CODEBUILD_SOURCE_VERSION` environment variable returns commit hash(example: `6548dbc49fe57e1fe7507a7a4b815639a62e9f90`) in a batch build when triggered by a pull request.

`CODEBUILD_WEBHOOK_TRIGGER` environment variable rerurns `{event_name}/{event_variable}`(example `pr/123`) in both normal build and batch build.

> CODEBUILD_WEBHOOK_TRIGGER
Shows the webhook event that triggered the build. This variable is available only for builds triggered by a webhook. The value is parsed from the payload sent to CodeBuild by GitHub, GitHub Enterprise Server, or Bitbucket. The value's format depends on what type of event triggered the build.
For builds triggered by a pull request, it is pr/pull-request-number.
For builds triggered by creating a new branch or pushing a commit to a branch, it is branch/branch-name.
For builds triggered by a pushing a tag to a repository, it is tag/tag-name.

https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-env-vars.html

Therefore, use `CODEBUILD_WEBHOOK_TRIGGER` environment variable so that danger works only when event_type is pr.

### CODE REVIEW

**Comment by orta** [comment]
Ah, I don't know enough about codebuild to know if this is a breaking change - can people self host?

**Comment by tomoya-yoshida-dwango** [comment]
> Ah, I don't know enough about codebuild to know if this is a breaking change - can people self host?

Yes, we can.
We are using codebuild.
It is working.

**Comment by orta** [comment]
If you can self-host then there may be cases where this new code breaks old builds - any chance you can make it backwards compatible?

**Comment by tomoya-yoshida-dwango** [comment]
For safety, if you want to keep the old ones working, I can implement it.

`CODEBUILD_BATCH_BUILD_IDENTIFIER` environment variable seems to be able to determine the mode of the code build, so use this to maintain backward compatibility.

**Comment by tomoya-yoshida-dwango** [comment]
Or is it better to have backward compatibility with a new environment variable that is not a `CODEBUILD_BATCH_BUILD_IDENTIFIER` environment variable?

**Comment by orta** [comment]
Yep, keep `CODEBUILD_WEBHOOK_TRIGGER` working if `CODEBUILD_WEBHOOK_TRIGGER` is not present

**Comment by tomoya-yoshida-dwango** [comment]
@orta 
`CODEBUILD_WEBHOOK_TRIGGER` environment variable always returns a value at coudebuild when created PR.(ex `pr/121`)

`CODEBUILD_BATCH_BUILD_IDENTIFIER` returns a value only with batch build(ex `build1`)

I implement it has backward compatibility depending on the present `CODEBUILD_BATCH_BUILD_IDENTIFIER`.
Please review 🙇

**Comment by orta** [comment]
Looks great, sorry of the delay!

**Pull request merged**
