### PR TITLE
Added protect_files method and plugins and more

### LINKED ISSUE #72: Support locked files
```ruby
unless has_org_access? "Artsy"
  protect_files(path: "**/*.gemspec", message: "Submit an issue instead of changing dependencies via PRs")
end
```

Define files that can only be modified by developers with write access to the repo.

### PR DESCRIPTION
**Pull request by KrauseFx**
Fixes #72
and fixes https://github.com/danger/danger/issues/74
and more

### CODE REVIEW

**Comment by orta** [comment]
alright felix, what do we need to do to get this in?

**Comment by KrauseFx** [comment]
Ugh, need some more time to finish this up, will try to do that tomorrow :+1:

**Comment by KrauseFx** [comment]
Wait, this is actually ready and passes just fine locally on newer Ruby versions. Will update the syntax error on legacy Ruby

**Comment by KrauseFx** [comment]
Alright, pushed a new commit, when the tests pass, please review and merge if appropriate :rocket:

**Comment by KrauseFx** [comment]
Alright, it failed for another reason now: 
```
Found 1 error(s) and I don't have write access to the PR set a PR status. if [ -z "$DANGER_GITHUB_API_TOKEN" ]; then echo "skipping fork of danger on CI"; else bundle exec danger; fi returned exit code 1
```

**Comment by orta** [comment]
Same for all your PRs: `Raising error 'Please include a CHANGELOG entry'`

**Comment by KrauseFx** [comment]
Working on it now :+1:

**Comment by KrauseFx** [comment]
Not sure if I did the changelog right. Tbh it's very unclear of what to expect for contributers, we should add some more information to the file itself on how to add this :+1:

**Comment by orta** [comment]
I don't see any changelog changes in the diff? It's just a file, could do with adding `master` at the top though

**Comment by KrauseFx** [comment]
Ugh, what's wrong here

**Comment by KrauseFx** [comment]
Pushed now, sorry

**Comment by orta** [comment]
Cool, let's do it

**Comment by KrauseFx** [comment]
@orta your browser plugin doesn't work :wink:

**Pull request merged**
