### PR TITLE
PR labels in DSL

### LINKED ISSUE #50: Expose PR labels
I'd be nice to have a custom variable in DSL to get the PR labels. Probably not super important, since you should be able to get that from `env.request_source.pr_json`.

### PR DESCRIPTION
**Pull request by marcelofabri**
Needs tests, just wanted to open to see if it's on the right direction.

Eventually will fix #50

### CODE REVIEW

**Comment by orta** [comment]
Yep, I think'd be it :+1:

**Comment by marcelofabri** [comment]
@orta Should I fix the offenses Rubocop is finding? They're from previous commits:

```
Offenses:
lib/danger/runner.rb:20:1: C: Extra blank line detected.
lib/danger/runner.rb:24:81: C: Avoid comma after the last item of an array.
        ['--head=[master|dev|stable]', 'A branch/tag/commit to use as the head'],
                                                                                ^
lib/danger/runner.rb:28:1: C: Extra blank line detected.
24 files inspected, 3 offenses detected
RuboCop failed!
```

Also, do you think theses tests are enough?

**Comment by orta** [comment]
Yeah, I think that was missed during the move to danger/danger before I set up all the CI!

**Comment by marcelofabri** [comment]
Fixed the violations, but CI is now failing because of a missing `DANGER_GITHUB_API_TOKEN`. Should that be necessary even for open source project?

**Comment by orta** [comment]
Yeah, to access the GitHub API it's required ( non-auth requests are per IP, and as this is ran on community hardware the IP is always fully auth'd out )

I'll investigate, I'm sure I added all the EN vars

**Comment by orta** [comment]
Oh, hrm. Well here's a complication. These CI instances are running from _your fork_.

**Comment by marcelofabri** [comment]
The Circle CI one seems to, but not the Travis one. Maybe because I've setup my fork on Circle CI. I'll delete that.

**Comment by marcelofabri** [comment]
From [Travis docs](https://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables):

> Encrypted environment variables are not available to pull requests from forks due to the security risk of exposing such information to unknown code.

**Comment by orta** [comment]
I've started opening the env vars for the danger bots, this is fine for these repos, but might make adoption harder.

**Comment by orta** [comment]
Alright, the fix for Circle is in master now

**Comment by marcelofabri** [comment]
:tada:

**Pull request merged**
