### PR TITLE
Fix Danger::RequestSources::GitLab#setup_danger_branches

### PR DESCRIPTION
**Pull request by rymai**
Fixes https://github.com/danger/danger/issues/1193.

///////////////////⚡///////////////////

# 🚫 AWESOME A PR!

- You can just delete all of this and start your PR text anytime -

Hello there, just a quick pre-warning of some of the Danger rules we run on Danger PRs.

The big one is we request that every code change to Danger include a CHANGELOG entry, 
this is so that:

1. People know what changes are between versions
2. Orta doesn't get all the credit for other people's work

Danger will look for a modification to the `CHANGELOG.md` when there are changes including
`lib/*` - if you're fixing unreleased code, or doing a simple typo change, you can
include `#trivial` in the title or the body of the PR and this is skipped.

We also request that you fill in the body of your PR, a title should be tweet length, but
ideally you can explain the PRs reasoning in the body. We look that it's longer than 5 chars.

Other than that, a lot of the other Danger rules are trickier to trigger so we can address
them as they come up!

❤ THANKS FOR HELPING OUT :D 

///////////////////⚡///////////////////

### CODE REVIEW

**Comment by danger-public** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Tests have failed, see below for more information.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Tests were not updated</td>
    </tr>
  </tbody>
</table>

### Tests: 

File | Name|
--- | ---|
<a href='https://github.com/rymai/danger/blob/33f4341b5eab7906c1330aa6ecece66851b6f711/./spec/lib/danger/request_sources/gitlab_spec.rb'>gitlab_spec.rb</a> | Danger::RequestSources::GitLab valid server response setups the danger branches|
<a href='https://github.com/rymai/danger/blob/33f4341b5eab7906c1330aa6ecece66851b6f711/./spec/lib/danger/request_sources/gitlab_spec.rb'>gitlab_spec.rb</a> | Danger::RequestSources::GitLab valid server response raise error on empty MR|


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by danger-public** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Tests have failed, see below for more information.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Tests were not updated</td>
    </tr>
  </tbody>
</table>

### Tests: 

File | Name|
--- | ---|
<a href='https://github.com/rymai/danger/blob/33f4341b5eab7906c1330aa6ecece66851b6f711/./spec/lib/danger/request_sources/gitlab_spec.rb'>gitlab_spec.rb</a> | Danger::RequestSources::GitLab valid server response raise error on empty MR|
<a href='https://github.com/rymai/danger/blob/33f4341b5eab7906c1330aa6ecece66851b6f711/./spec/lib/danger/request_sources/gitlab_spec.rb'>gitlab_spec.rb</a> | Danger::RequestSources::GitLab valid server response setups the danger branches|


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by orta** [comment]
OK, cool - this looks good to me ( I'll merge & deploy this once #1195 is in and I've handled the conflicts)

**Comment by orta** [comment]
Merge on green

**Pull request merged**
