### PR TITLE
adds staging command for local only run

### PR DESCRIPTION
**Pull request by olbrichj**
Since until now `local` and `pr` require a working remote git, this adds the ability to run the current branch against a local master. [#1179](https://github.com/danger/danger/issues/1179).
///////////////////⚡///////////////////

### CODE REVIEW

**Comment by danger-public** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Tests were not updated</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by olbrichj** [comment]
Since I've added a new specfile and did not modify any, the warning above feels misleeding. Maybe the dangerfile should also be changed to check for new files in `spec`.

**Comment by orta** [comment]
Huh, interesting, this is like a shockingly low amount of code

**Comment by orta** [comment]
Looks good - we'll merge on green

**Pull request merged**
