### PR TITLE
Patch/environment manager specs

### PR DESCRIPTION
**Pull request by JuanitoFatas**
This PR adds some tests for `EnvironmentManager` class.

Specs just quit exceptionally by RSpec JUnit Formatter:

```
$ bundle exec rspec spec/lib/danger/danger_core/environment_manager_spec.rb:176

bundler: failed to load command: rspec (/Users/Juan/.gem/ruby/2.2.5/bin/rspec)
NoMethodError: undefined method `xml_dump_' for #<RSpecJUnitFormatter:0x007ff9011e44a0>
  /Users/Juan/.gem/ruby/2.2.5/gems/rspec_junit_formatter-0.2.3/lib/rspec_junit_formatter.rb:29:in `block in xml_dump_examples'
  /Users/Juan/.gem/ruby/2.2.5/gems/rspec_junit_formatter-0.2.3/lib/rspec_junit_formatter.rb:28:in `each'
  /Users/Juan/.gem/ruby/2.2.5/gems/rspec_junit_formatter-0.2.3/lib/rspec_junit_formatter.rb:28:in `xml_dump_examples'
  /Users/Juan/.gem/ruby/2.2.5/gems/rspec_junit_formatter-0.2.3/lib/rspec_junit_formatter.rb:23:in `block in xml_dump'
  /Users/Juan/.gem/ruby/2.2.5/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `call'
  /Users/Juan/.gem/ruby/2.2.5/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `_nested_structures'
  /Users/Juan/.gem/ruby/2.2.5/gems/builder-3.2.2/lib/builder/xmlbase.rb:68:in `tag!'
  /Users/Juan/.gem/ruby/2.2.5/gems/builder-3.2.2/lib/builder/xmlbase.rb:93:in `method_missing'
  /Users/Juan/.gem/ruby/2.2.5/gems/rspec_junit_formatter-0.2.3/lib/rspec_junit_formatter.rb:20:in `xml_dump'
  /Users/Juan/.gem/ruby/2.2.5/gems/rspec_junit_formatter-0.2.3/lib/rspec_junit_formatter/rspec3.rb:19:in `dump_summary'
  /Users/Juan/.gem/ruby/2.2.5/gems/rspec-core-3.5.3/lib/rspec/core/reporter.rb:201:in `block in notify'
  /Users/Juan/.gem/ruby/2.2.5/gems/rspec-core-3.5.3/lib/rspec/core/reporter.rb:200:in `each'
  /Users/Juan/.gem/ruby/2.2.5/gems/rspec-core-3.5.3/lib/rspec/core/reporter.rb:200:in `notify'
  /Users/Juan/.gem/ruby/2.2.5/gems/rspec-core-3.5.3/lib/rspec/core/reporter.rb:179:in `block in finish'
  /Users/Juan/.gem/ruby/2.2.5/gems/rspec-core-3.5.3/lib/rspec/core/reporter.rb:187:in `close_after'
  /Users/Juan/.gem/ruby/2.2.5/gems/rspec-core-3.5.3/lib/rspec/core/reporter.rb:168:in `finish'
  /Users/Juan/.gem/ruby/2.2.5/gems/rspec-core-3.5.3/lib/rspec/core/reporter.rb:79:in `ensure in report'
  /Users/Juan/.gem/ruby/2.2.5/gems/rspec-core-3.5.3/lib/rspec/core/reporter.rb:79:in `report'
  /Users/Juan/.gem/ruby/2.2.5/gems/rspec-core-3.5.3/lib/rspec/core/runner.rb:111:in `run_specs'
  /Users/Juan/.gem/ruby/2.2.5/gems/rspec-core-3.5.3/lib/rspec/core/runner.rb:87:in `run'
  /Users/Juan/.gem/ruby/2.2.5/gems/rspec-core-3.5.3/lib/rspec/core/runner.rb:71:in `run'
  /Users/Juan/.gem/ruby/2.2.5/gems/rspec-core-3.5.3/lib/rspec/core/runner.rb:45:in `invoke'
  /Users/Juan/.gem/ruby/2.2.5/gems/rspec-core-3.5.3/exe/rspec:4:in `<top (required)>'
  /Users/Juan/.gem/ruby/2.2.5/bin/rspec:23:in `load'
  /Users/Juan/.gem/ruby/2.2.5/bin/rspec:23:in `<top (required)>'
Coverage report generated for RSpec to /Users/Juan/dev/danger/coverage. 877 / 2384 LOC (36.79%) covered.
```

I cannot run the specs `¯\_(ツ)_/¯`...

### CODE REVIEW

**Comment by orta** [comment]
Ah, well, then, I think it's fine to remove the library and the danger plugin for now

**Comment by JuanitoFatas** [comment]
> Ah, well, then, I think it's fine to remove the library and the danger plugin for now

```ruby
describe "#pr?" do
    it "returns true if has a ci source" do
      with_travis_setup_and_is_a_pull_request do |env|
        env_manager = Danger::EnvironmentManager.new(env, testing_ui)
        expect(env_manager.pr?).to eq true
      end
    end
  end
```

It still quits without exception when executed this line:

```ruby
env_manager = Danger::EnvironmentManager.new(env, testing_ui)
```

Very weird, 😓

**Comment by JuanitoFatas** [comment]
I found out why:

```ruby
RequestSources::RequestSource.available_request_sources.each do |klass|
  next unless self.ci_source.supports?(klass)

  request_source = klass.new(self.ci_source, env)
  next unless request_source.validates_as_ci?
  next unless request_source.validates_as_api_source?
  self.request_source = request_source
end

raise_error_for_no_request_source(env, ui) unless self.request_source
```

The request source did not pass the tests:

- `request_source.validates_as_ci?`
- `request_source.validates_as_api_source?`

So `request_source` is `nil`.

Then we display error by cork, then `exit(1)`. In our test setup, we [redirect all cork outputs to `StringIO`](https://github.com/danger/danger/blob/8a5e5cb7d72c2a43a58e9e1a29f7218026abbf2c/spec/spec_helper.rb#L44), which caused the silent failure 😓

**Comment by orta** [comment]
Ouch! - I wonder if we could do something around that

**Comment by orta** [comment]
Maybe there's another way to exit, other than `exit`? :D

**Comment by JuanitoFatas** [comment]
> Ouch! - I wonder if we could do something around that

Maybe we can raises an error when `reqeust_source` cannot be attained. Later PR?

> Maybe there's another way to exit, other than exit? :D

Actually, all methods (fail, raise, abort), uses `exit` under the hood. So the problem is mainly I'm not familiar with the test setup. This PR is good to merge.

**Comment by orta** [comment]
👍

**Pull request merged**
