### PR TITLE
Use html comment to identify comments from danger

### PR DESCRIPTION
**Pull request by Ram-Z**
Avoid adding the "Generated by :no_entry_sign: " footer in inline comments even when there is markdown.

This is using a html comment instead of a `data-meta` attribute.

Arguable the `data-meta` from the table above could be remove if this is printed always, or the html comment could be made to only print when there is markdown or no table, suggestions are welcome.

### CODE REVIEW

**Comment by Ram-Z** [comment]
@orta Any thoughts on this MR?

**Comment by orta** [comment]
Yeah, this seems good to me 👍🏻

**Comment by orta** [comment]
I don't have time to release this though, so will just merge

**Comment by Ram-Z** [comment]
Thanks.

**Pull request merged**
