### PR TITLE
Fix VSTS comments

### PR DESCRIPTION
**Pull request by cyupa**
This fixes the VSTS commenting logic.

At this point, the VSTS module looks for the `new_comment` flag to decide if it should post a new comment or not - which is set to false.
It then tries to update the previous comment which doesn't exist for a new pull request.

The fix looks for any comment posted by danger to determine if a previous comment was posted and tries to update it.
If no comment added by danger is found, it adds a new comment.

### CODE REVIEW

**Comment by cyupa** [comment]
@orta sorry for the messy way of doing this. I have limited experience with Ruby and it was mostly a trial and error process 😄

**Comment by orta** [comment]
Nice one - I think you're gonna want a test for this ( go check the github/gitlab/bitbucket test files, they'll basically be something you can copy & edit slightly) as you don't want that breaking in the future.

Looks good to me though, I also don't mind about the commit faffing, I can just use the GitHub button to squash all commits

**Comment by cyupa** [comment]
Cool, I'll look at how I can update the tests to cover this. I've tested the implementation against a VSTS project, hence the commit madness 💩

**Comment by cyupa** [comment]
@orta This should do it. Thanks!

**Comment by orta** [comment]
Congrats @cyupa - you did a great job there

**Comment by cyupa** [comment]
Thanks again for this awesome tool @orta 👍

**Comment by orta** [comment]
Shipped as 5.5.3

**Pull request merged**
