### PR TITLE
Replaced … with ... #trivial

### PR DESCRIPTION
**Pull request by KrauseFx**
These close 3 dots look weird

### CODE REVIEW

**Comment by orta** [comment]
Any specific reason? I went out of my way to use the real unicode characters here.

**Comment by KrauseFx** [comment]
These close 3 dots look weird. Any reason why we should use them? Just having 3 dots looks better :+1:

**Comment by KrauseFx** [comment]
Ready to merge @orta :rocket:

**Comment by KrauseFx** [comment]
:dancers:

**Pull request merged**
