### PR TITLE
Added check for gemspec file for external contributors #trivial

### PR DESCRIPTION
**Pull request by KrauseFx**
Changelog here

### CODE REVIEW

**Comment by jeroenvisser101** [comment]
No? :sob:

**Comment by orta** [comment]
This'll make much more sense once #128 is in

**Comment by jeroenvisser101** [comment]
Ah, yes!

**Comment by KrauseFx** [comment]
Yeah :+1: It's just that I often receive PRs that casually add a dependency to nokogiri :stuck_out_tongue_winking_eye:

**Comment by orta** [comment]
haha, you could add a specific check in the `Gemfile.lock` ;)

**Comment by KrauseFx** [comment]
I don't have Gemfile.lock in version control for my gems

**Pull request merged**
