### PR TITLE
Add support for App Center

### PR DESCRIPTION
**Pull request by cojoj**
Added Visual Studio App Center as a new CI source. It's a copy of #1057, but with resolved missing PR id. It's also heavily based on solution introduced in #892.

I haven't added any tests, because I have no clue how to do it in order to fake the networking and `DANGER_GITHUB_API_TOKEN` 😢

I hope this will be just a _temporary_ solution and soon we'd get a proper PR ID directly in App Center's environmental variables. I've created a [feature request in their repo](https://github.com/Microsoft/appcenter/issues/79).

### CODE REVIEW

**Comment by orta** [comment]
Seems good to me, have you tried it?

**Comment by cojoj** [comment]
Yes, I've integrated my fork with our project, though I can't give you link or anything as it's a privte repo 🙈 At least, I can share a screenshot.

zrzut ekranu 2019-02-22 o 19 38 59

I'd love to add some test to this, but I'm not sure if it's even possible since Codeship is missing tests as well.

**Comment by orta** [comment]
I'm OK skipping tests for that bit

**Comment by cojoj** [comment]
Hey @orta do we want anything more in here, or is it ready to be merged?

**Comment by orta** [comment]
Nope, I just didn't come back once it was green 👍

**Pull request merged**
