### PR TITLE
Drop support for Ruby 2.4, support Ruby 2.7+

### PR DESCRIPTION
**Pull request by mathroule**
Require Ruby version 2.7+. Ruby 2.6 has reached end of life: https://www.ruby-lang.org/en/downloads/branches. This change is a prerequisite to https://github.com/danger/danger/pull/1377.

Changes:
- Use Ruby 2.7
- Use bundler 2.3.20

AppVeyor project configuration needs to be changed to use Visual Studio 2022 (or at least 2019) to support Ruby 2.7 (https://www.appveyor.com/docs/windows-images-software/#ruby).
Screen Shot 2022-08-22 at 19 19 47

### CODE REVIEW

**Review by Kaspik — APPROVED** [review]
LGTM, soudn good. We should add support (tests) for 3.0+ too.

**Comment by mathroule** [comment]
> LGTM, soudn good. We should add support (tests) for 3.0+ too.

Danger is tested against Ruby 3.+ on GitHub Actions: https://github.com/danger/danger/blob/master/.github/workflows/CI.yml#L10

I updated the CircleCI config file, but Danger appears to be not built anymore on this platform.

**Comment by mathroule** [comment]
@orta could you please help with the AppVeyor project settings?

**Comment by Kaspik** [comment]
I think we can skip AppVeyor completely as we moved to Github Actions?

**Comment by mathroule** [comment]
> I think we can skip AppVeyor completely as we moved to Github Actions?

I'm not against merging the PR as is. But it's just a matter of changing an option in AppVeyor to keep the compatibility.

**Comment by orta** [comment]
Updated to VS 2022 - we have the appveyor for testing windows compat, dropping that is OK if we check on windows using GitHub Actions  👍🏻

**Comment by orta** [comment]
This'll have to be a semver major bump alas

**Comment by mathroule** [comment]
> Updated to VS 2022 - we have the appveyor for testing windows compat, dropping that is OK if we check on windows using GitHub Actions 👍🏻

@orta Windows checks done on GitHub Actions in https://github.com/danger/danger/pull/1381.

**Comment by orta** [comment]
Cool, I've carved out some time to go through all this tomorrow 👍🏻

**Pull request merged**
