### PR TITLE
added url scheme in host name. Added support for backword compatibility

### PR DESCRIPTION
**Pull request by RishabhTayal**
///////////////////⚡///////////////////

# 🚫 AWESOME A PR!

Added fix for https://github.com/danger/danger/issues/784.

I am not a ruby expert so I am not sure if this code will work 💯%.

///////////////////⚡///////////////////

### CODE REVIEW

**Comment by orta** [comment]
This looks great, 👍 - to add a test to this, add some [space here](https://github.com/danger/danger/blob/master/spec/lib/danger/request_sources/bitbucket_server_api_spec.rb#L12)

Then add something like this:
```
    it "handles http hosts" do
        env = stub_env
        env["DANGER_BITBUCKETSERVER_HOST"] = "http://my_url..."
        api = described_class.new("danger", "danger", 1, env)
       expect(api.pr_api_endpoint).to.equal("http://my_url/things/pull-requests/1")
   end
```

**Comment by orta** [comment]
And that fail is legit - your changes _would_ make changes to that test 👍

**Comment by RishabhTayal** [comment]
@orta I added a test case and CHANGELOG.md. Please review.

**Comment by orta** [comment]
You still have two failing tests:

screen shot 2017-04-17 at 14 55 46

**Comment by RishabhTayal** [comment]
@orta Fixed!

**Comment by orta** [comment]
Awesome, this looks good. I'll ship it 👍

**Comment by orta** [comment]
Alright - this has gone off in 5.0.1 - thanks @RishabhTayal, this was a great PR 
also, I've invited you to the org, as a part of [Moya Community Continuity](https://github.com/Moya/contributors/issues/6) - you're welcome to participate in PRs and help out at a level that works for you.

**Comment by RishabhTayal** [comment]
Awesome. I not sure if I have the skills to contribute in ruby, but definitely going to try and contribute. +1

**Comment by RishabhTayal** [comment]
@orta found a issue where it's always using ssl while making http call. refer: [bitbucket_server_api.rb](https://github.com/danger/danger/blob/master/lib/danger/request_sources/bitbucket_server_api.rb#L60). Will create another PR to fix this.

**Comment by orta** [comment]
👍

**Pull request merged**
