### PR TITLE
[#447] Update CI Sources that support GitLab

### PR DESCRIPTION
**Pull request by k0nserv**
Also cleans up the tests a bit and expands them
to test a larger surface area.

closes: #447

### CODE REVIEW

**Comment by k0nserv** [comment]
Oops, forgot to update the teamcity docs

**Comment by orta** [comment]
10/10

**Comment by orta** [comment]
solid work

**Comment by orta** [comment]
You could call this one trivial I think - fits inside the big "gitlab" entry

**Comment by k0nserv** [comment]
Just added a CHANGELOG entry

**Comment by k0nserv** [comment]
image

Coverage improved pretty much for CI sources too. I'll take a pass at upping the coverage for the others at some point too

**Comment by k0nserv** [comment]
Rebased

**Pull request merged**
