### PR TITLE
Adds Chandler to run on every tag

### PR DESCRIPTION
**Pull request by orta**
I don't want more process on releases, so this let's travis and Chandler do everything for us 👍

### CODE REVIEW

**Comment by orta** [comment]
Chandler is what turns the CHANGELOG into GitHub Release Notes 👍

**Comment by JuanitoFatas** [comment]
@orta Do you use `rake release` to release a new version? Then we can [hook chandler with rake release](https://github.com/mattbrictson/chandler#2-modify-the-rakefile) and we don't need travis to do for us.

**Comment by orta** [comment]
I do, but then I have to expose my ( or another ) github access token in my ENV, this just automates that away for us all

**Comment by orta** [comment]
Cool, update looks good to me

**Pull request merged**
