### PR TITLE
Use reviews API from octokit;

### PR DESCRIPTION
**Pull request by Antondomashnev**
Danger's pull request reviews support has been done while the API was in beta testing. Now it's released and [octokit](https://github.com/octokit/octokit.rb) is updated with that API. No need for custom methods anymore 😄

### CODE REVIEW

**Comment by orta** [comment]
I think we'll need to bump the gem spec's version of Octokit too 👍 

Otherwise looks great

**Comment by Antondomashnev** [comment]
> Please include a CHANGELOG entry. 

Hm, is that a bug or I'm missing something?

**Comment by orta** [comment]
Interesting, it could be - yeah

**Comment by orta** [comment]
Probably just CI on an older commit, it's gone now

**Comment by Antondomashnev** [comment]
> Probably just CI on an older commit, it's gone now

Yeah seems like not a Danger related 👍

**Comment by orta** [comment]
Think you can remove this rubocop error: `lib/danger/commands/init.rb:185:21: C: Prefer using YAML.safe_load over YAML.load.` ?

**Comment by Antondomashnev** [comment]
@orta sure thing

**Comment by Antondomashnev** [comment]
@orta hah, it's not that easy, because the method is not available for ruby 2.0 😄

**Comment by orta** [comment]
Ah sorry, yeah, I meant to just add an ignore for it :D

I just merged a PR that did that - want to revert back to 0cb6141 and then merge master, then you are good to go and I'll make a release

**Comment by Antondomashnev** [comment]
@orta done 😉

**Comment by orta** [comment]
Cool - shipped!

**Pull request merged**
