### PR TITLE
[WIP] Add inline comment feature for BBS

### PR DESCRIPTION
**Pull request by RishabhTayal**
This PR is work in progress for implementing inline comment for Bitbucket Server. There is an [issue](https://github.com/danger/danger/issues/806) opened to track this PR.

Need help from other contributors to implement this. I am not a ruby expert but I think I can start somewhere.

Here are some of the answers I need to understand the workflow if someone can help.

- [ ] Figure out when to call `post_comment` and when to call `post_inline_comment` methods.
- [ ] Get values for `line`, `lineType`, `fromHash`, `path`, `srcPath`, `toHash` in order to call the bitbucket API ([Reference](https://developer.atlassian.com/static/rest/bitbucket-server/5.0.0/bitbucket-rest.html#idm45659055842560)).
- [ ] Update [danger.systems](danger.systems) website to reflect this feature implementation.

### CODE REVIEW

**Comment by orta** [comment]
This is a good start, I'd look into taking the comment generation work from the github client and turning it into a generic one (there are a lot of places where this stuff can get complex, so re-use existing code)

**Comment by RishabhTayal** [comment]
Thanks. Appreciate your help.

**Comment by netbe** [comment]
@RishabhTayal need any help on this? We're integrating danger with BBS and that feature would be great.

also looking for approvals like in https://wiki.jenkins-ci.org/display/JENKINS/Bitbucket+Approve+Plugin, @orta does Danger already support this?

**Comment by orta** [comment]
I don't think Danger supports the commit status API for anything other than GitHub - probably just needs a single API call at the right place though 👍

**Comment by orta** [comment]
This has been idle for 2 month @RishabhTayal do you still have time to take a look at this? I'd rather not leave it as a hung PR as it means someone else might not take a stab at it

**Comment by RishabhTayal** [comment]
Currently I am not getting enough time to work on this. You can close it.

**Comment by orta** [comment]
No worries, never feel guilty for not contributing to open source 👍

**Comment by RishabhTayal** [comment]
Thanks. I hope I can work on it in near future.

**Pull request closed without merging**
