### PR TITLE
Adding Jenkins provider

### PR DESCRIPTION
**Pull request by marcelofabri**
This will only work if using [this plugin](https://wiki.jenkins-ci.org/display/JENKINS/GitHub+pull+request+builder+plugin) to build PR on Jenkins, but that seems to be the most used one.

### CODE REVIEW

**Comment by orta** [comment]
Rebuilding CI, failure was legit ( danger was complaining about the lack of a description ) and now there is one.

**Comment by orta** [comment]
Cool, this is good to go if you're happy - needs a rebase first.

**Comment by marcelofabri** [comment]
Rebased, kept it in 0.3.0 section :pray:

**Comment by orta** [comment]
Heh, that ship has sailed -  https://rubygems.org/gems/danger

But I'm chill, it can move in time.

**Comment by marcelofabri** [comment]
But it doesn't seem to have a tag? Does that make sense?

**Pull request merged**
