### PR TITLE
Use HTTPS links where applicable

### PR DESCRIPTION
**Pull request by allewun**
http -> https :)

### CODE REVIEW

**Comment by orta** [comment]
Yep, perfect, merge on green

For the first 3 years I couldn't use https on danger.systems - now we can 🎉

**Comment by allewun** [comment]
@orta looks like I need an approval to merge

**Comment by allewun** [comment]
And you can update this guy too:

image

**Comment by orta** [comment]
cool, makes sense - yeah, will get that

**Pull request merged**
